# Generated by Django 4.0.4 on 2022-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('academia', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('categoriaEdad', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
                ('categoriaPeso', models.CharField(max_length=50)),
                ('comprobantePago', models.ImageField(upload_to='comprobantes/')),
                ('verificado', models.BooleanField()),
            ],
        ),
    ]
