# Generated by Django 4.0.4 on 2022-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_competitor_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='comprobantePago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
