# Generated by Django 4.0.4 on 2022-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_competitor_comprobantepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='peso',
        ),
        migrations.AddField(
            model_name='competitor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='cinturon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='documento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='nombres',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='academia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='categoriaEdad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='categoriaPeso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='verificado',
            field=models.BooleanField(default=b'I00\n'),
        ),
    ]
