# Generated by Django 4.0.4 on 2022-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_competitor_genero_alter_competitor_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='academia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='categoriaEdad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='categoriaPeso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='cinturon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='comprobantePago',
            field=models.ImageField(blank=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='documento',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='fechaNacimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='genero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='nombres',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
