# Generated by Django 4.0.4 on 2022-06-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_competitor_academia_alter_competitor_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='comprobantePago',
            field=models.ImageField(blank=True, upload_to='media/comprobantes/'),
        ),
    ]
