# Generated by Django 4.0.4 on 2022-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_alter_competitor_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='comprobantePago',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
