# Generated by Django 4.0.4 on 2022-08-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_alter_competitor_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='documento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
