# Generated by Django 4.0.4 on 2022-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_competitor_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='igtag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='competitor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
